import json
import os
import re
import sys

def main():
    # Paths relative to the script location (firmware/stinger/tools/)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    json_file = os.path.join(script_dir, '..', 'master_pins.json')
    pin_map_h = os.path.join(script_dir, '..', 'main', 'pin_map.h')
    spec_md = os.path.join(script_dir, '..', '..', '..', 'SPEC.md')

    print(f"Reading pin definitions from: {json_file}")
    try:
        with open(json_file, 'r') as f:
            data = json.load(f)
    except FileNotFoundError:
        print(f"Error: {json_file} not found.", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"Error parsing JSON: {e}", file=sys.stderr)
        sys.exit(1)

    pins = data.get('pins', [])
    if not pins:
        print("Warning: No pins found in YAML.", file=sys.stderr)

    # 1. Generate pin_map.h
    print(f"Generating {pin_map_h}...")
    h_content = "/* \n"
    h_content += " * Auto-generated by tools/generate_pins.py from master_pins.yaml\n"
    h_content += " * DO NOT EDIT THIS FILE DIRECTLY.\n"
    h_content += " */\n"
    h_content += "#ifndef PIN_MAP_H\n#define PIN_MAP_H\n\n"
    
    for pin in pins:
        name = pin['name']
        gpio = pin['gpio']
        desc = pin.get('desc', '')
        h_content += f"#define {name:20} {int(gpio):<3} /* {desc} */\n"
    
    h_content += "\n#endif /* PIN_MAP_H */\n"

    os.makedirs(os.path.dirname(pin_map_h), exist_ok=True)
    with open(pin_map_h, 'w') as f:
        f.write(h_content)

    # 2. Update SPEC.md
    print(f"Updating {spec_md}...")
    md_table = "| Pin Name | GPIO | Description/Note |\n"
    md_table += "|---|---|---|\n"
    for pin in pins:
        desc = pin.get('desc', '')
        md_table += f"| `{pin['name']}` | GPIO {pin['gpio']} | {desc} |\n"

    try:
        with open(spec_md, 'r') as f:
            spec_content = f.read()
            
        # The regex strictly targets everything between <!-- PINS_START --> and <!-- PINS_END -->
        pattern = re.compile(r'(<!-- PINS_START -->\n(?:.*?))(<!-- PINS_END -->)', re.DOTALL)
        
        # Determine what we are replacing the old block with:
        # We preserve the START marker + warning text if it was there, but it's simpler to just replace the whole inner block
        replacement = f"<!-- PINS_START -->\n<!-- The table below is auto-generated from firmware/stinger/master_pins.yaml during build. Do not edit. -->\n{md_table}"
        
        new_spec, count = pattern.subn(rf'{replacement}\g<2>', spec_content)
        
        if count == 0:
            print(f"Warning: Could not find <!-- PINS_START --> and <!-- PINS_END --> markers in {spec_md}", file=sys.stderr)
        else:
            with open(spec_md, 'w') as f:
                f.write(new_spec)
                
    except FileNotFoundError:
        print(f"Warning: {spec_md} not found. Skipping documentation update.", file=sys.stderr)
    except Exception as e:
        print(f"Error updating SPEC.md: {e}", file=sys.stderr)

if __name__ == '__main__':
    main()
