/* 
 * Auto-generated by tools/generate_pins.py from master_pins.yaml
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
#ifndef PIN_MAP_H
#define PIN_MAP_H

#define PIN_USB_D_MINUS      19  /* USB D- */
#define PIN_USB_D_PLUS       20  /* USB D+ */
#define PIN_I2S_BCLK         38  /* I2S BCLK (Audio Data) */
#define PIN_I2S_LRCK         39  /* I2S LRCK (Audio Data) */
#define PIN_I2S_DOUT         40  /* I2S DOUT (Audio Data) */
#define PIN_I2S_DIN          41  /* I2S DIN (Audio Data) */
#define PIN_I2S_MCLK         0   /* I2S MCLK (CLK_OUT1. 256xFs = 12.288 MHz) */
#define PIN_I2C_SDA          4   /* I2C SDA (Control) */
#define PIN_I2C_SCL          5   /* I2C SCL (Control) */
#define PIN_SPI2_CS          10  /* SPI2 CS (MicroSD) */
#define PIN_SPI2_MOSI        11  /* SPI2 MOSI (MicroSD) */
#define PIN_SPI2_SCK         12  /* SPI2 SCK (MicroSD) */
#define PIN_SPI2_MISO        13  /* SPI2 MISO (MicroSD) */
#define PIN_SPI3_CS          21  /* SPI3 CS (E-Paper) on non-strapping pin */
#define PIN_SPI3_DIN         16  /* SPI3 DIN (E-Paper) */
#define PIN_SPI3_CLK         17  /* SPI3 CLK (E-Paper) */
#define PIN_SPI3_DC          18  /* SPI3 DC (E-Paper) */
#define PIN_SPI3_RST         7   /* SPI3 RST (E-Paper) */
#define PIN_SPI3_BUSY        6   /* SPI3 BUSY (E-Paper) */
#define PIN_MATRIX_ROW_0     1   /* Matrix Row 0 */
#define PIN_MATRIX_ROW_1     2   /* Matrix Row 1 */
#define PIN_MATRIX_ROW_2     42  /* Matrix Row 2 */
#define PIN_MATRIX_ROW_3     43  /* Matrix Row 3 */
#define PIN_MATRIX_COL_0     8   /* Matrix Col 0 */
#define PIN_MATRIX_COL_1     3   /* Matrix Col 1 */
#define PIN_MATRIX_COL_2     44  /* Matrix Col 2 */
#define PIN_MATRIX_COL_3     9   /* Matrix Col 3 */
#define PIN_ENC1_A           47  /* Encoder 1 A (Bank switching) */
#define PIN_ENC1_B           14  /* Encoder 1 B (Bank switching) */
#define PIN_ENC2_A           22  /* Encoder 2 A (SD Gain) */
#define PIN_ENC2_B           23  /* Encoder 2 B (SD Gain) */
#define PIN_SD_DETECT        26  /* SD Card Detect (Active low) */
#define PIN_STATUS_LED       48  /* Status RGB LED */

#endif /* PIN_MAP_H */
